//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Dlya_primera
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Оборудование.
    /// </summary>
    // *** Start programmer edit section *** (Оборудование CustomAttributes)

    // *** End programmer edit section *** (Оборудование CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОборудованиеE", new string[] {
            "ИнвНомер as \'Инв номер\'",
            "Название as \'Название\'",
            "Тип as \'Тип\'",
            "Тип.Название as \'Название\'",
            "Сотрудник as \'Сотрудник\'",
            "Сотрудник.ФИО as \'ФИО\'"}, Hidden=new string[] {
            "Тип.Название",
            "Сотрудник.ФИО"})]
    [MasterViewDefineAttribute("ОборудованиеE", "Тип", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Название")]
    [MasterViewDefineAttribute("ОборудованиеE", "Сотрудник", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    public class Оборудование : ICSSoft.STORMNET.DataObject
    {
        
        private string fИнвНомер;
        
        private string fНазвание;
        
        private IIS.Dlya_primera.Пользователь fСотрудник;
        
        private IIS.Dlya_primera.Тип fТип;
        
        private IIS.Dlya_primera.РабочееМесто fРабочееМесто;
        
        // *** Start programmer edit section *** (Оборудование CustomMembers)

        // *** End programmer edit section *** (Оборудование CustomMembers)

        
        /// <summary>
        /// ИнвНомер.
        /// </summary>
        // *** Start programmer edit section *** (Оборудование.ИнвНомер CustomAttributes)

        // *** End programmer edit section *** (Оборудование.ИнвНомер CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string ИнвНомер
        {
            get
            {
                // *** Start programmer edit section *** (Оборудование.ИнвНомер Get start)

                // *** End programmer edit section *** (Оборудование.ИнвНомер Get start)
                string result = this.fИнвНомер;
                // *** Start programmer edit section *** (Оборудование.ИнвНомер Get end)

                // *** End programmer edit section *** (Оборудование.ИнвНомер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Оборудование.ИнвНомер Set start)

                // *** End programmer edit section *** (Оборудование.ИнвНомер Set start)
                this.fИнвНомер = value;
                // *** Start programmer edit section *** (Оборудование.ИнвНомер Set end)

                // *** End programmer edit section *** (Оборудование.ИнвНомер Set end)
            }
        }
        
        /// <summary>
        /// Название.
        /// </summary>
        // *** Start programmer edit section *** (Оборудование.Название CustomAttributes)

        // *** End programmer edit section *** (Оборудование.Название CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string Название
        {
            get
            {
                // *** Start programmer edit section *** (Оборудование.Название Get start)

                // *** End programmer edit section *** (Оборудование.Название Get start)
                string result = this.fНазвание;
                // *** Start programmer edit section *** (Оборудование.Название Get end)

                // *** End programmer edit section *** (Оборудование.Название Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Оборудование.Название Set start)

                // *** End programmer edit section *** (Оборудование.Название Set start)
                this.fНазвание = value;
                // *** Start programmer edit section *** (Оборудование.Название Set end)

                // *** End programmer edit section *** (Оборудование.Название Set end)
            }
        }
        
        /// <summary>
        /// Оборудование.
        /// </summary>
        // *** Start programmer edit section *** (Оборудование.Сотрудник CustomAttributes)

        // *** End programmer edit section *** (Оборудование.Сотрудник CustomAttributes)
        [NotNull()]
        public virtual IIS.Dlya_primera.Пользователь Сотрудник
        {
            get
            {
                // *** Start programmer edit section *** (Оборудование.Сотрудник Get start)

                // *** End programmer edit section *** (Оборудование.Сотрудник Get start)
                IIS.Dlya_primera.Пользователь result = this.fСотрудник;
                // *** Start programmer edit section *** (Оборудование.Сотрудник Get end)

                // *** End programmer edit section *** (Оборудование.Сотрудник Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Оборудование.Сотрудник Set start)

                // *** End programmer edit section *** (Оборудование.Сотрудник Set start)
                this.fСотрудник = value;
                // *** Start programmer edit section *** (Оборудование.Сотрудник Set end)

                // *** End programmer edit section *** (Оборудование.Сотрудник Set end)
            }
        }
        
        /// <summary>
        /// Оборудование.
        /// </summary>
        // *** Start programmer edit section *** (Оборудование.Тип CustomAttributes)

        // *** End programmer edit section *** (Оборудование.Тип CustomAttributes)
        [NotNull()]
        public virtual IIS.Dlya_primera.Тип Тип
        {
            get
            {
                // *** Start programmer edit section *** (Оборудование.Тип Get start)

                // *** End programmer edit section *** (Оборудование.Тип Get start)
                IIS.Dlya_primera.Тип result = this.fТип;
                // *** Start programmer edit section *** (Оборудование.Тип Get end)

                // *** End programmer edit section *** (Оборудование.Тип Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Оборудование.Тип Set start)

                // *** End programmer edit section *** (Оборудование.Тип Set start)
                this.fТип = value;
                // *** Start programmer edit section *** (Оборудование.Тип Set end)

                // *** End programmer edit section *** (Оборудование.Тип Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Dlya_primera.РабочееМесто.
        /// </summary>
        // *** Start programmer edit section *** (Оборудование.РабочееМесто CustomAttributes)

        // *** End programmer edit section *** (Оборудование.РабочееМесто CustomAttributes)
        [Agregator()]
        [NotNull()]
        public virtual IIS.Dlya_primera.РабочееМесто РабочееМесто
        {
            get
            {
                // *** Start programmer edit section *** (Оборудование.РабочееМесто Get start)

                // *** End programmer edit section *** (Оборудование.РабочееМесто Get start)
                IIS.Dlya_primera.РабочееМесто result = this.fРабочееМесто;
                // *** Start programmer edit section *** (Оборудование.РабочееМесто Get end)

                // *** End programmer edit section *** (Оборудование.РабочееМесто Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Оборудование.РабочееМесто Set start)

                // *** End programmer edit section *** (Оборудование.РабочееМесто Set start)
                this.fРабочееМесто = value;
                // *** Start programmer edit section *** (Оборудование.РабочееМесто Set end)

                // *** End programmer edit section *** (Оборудование.РабочееМесто Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОборудованиеE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОборудованиеE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОборудованиеE", typeof(IIS.Dlya_primera.Оборудование));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Оборудование.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfОборудование CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfОборудование CustomAttributes)
    public class DetailArrayOfОборудование : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Dlya_primera.DetailArrayOfОборудование members)

        // *** End programmer edit section *** (IIS.Dlya_primera.DetailArrayOfОборудование members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Оборудование by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Оборудование.
        /// </summary>
        public DetailArrayOfОборудование(IIS.Dlya_primera.РабочееМесто fРабочееМесто) : 
                base(typeof(Оборудование), ((ICSSoft.STORMNET.DataObject)(fРабочееМесто)))
        {
        }
        
        public IIS.Dlya_primera.Оборудование this[int index]
        {
            get
            {
                return ((IIS.Dlya_primera.Оборудование)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Dlya_primera.Оборудование dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
